steps:
- emerge -b =sys-power-4.20/acpi_call-3.17
requires:
- category: "sys-kernel"
  version:  "4.20.6"
  name:     "linux-sabayon"
- category: "sys-kernel"
  version:  "4.20.6"
  name:     "sabayon-sources"

includes:
- /usr/portage/packages/.*

