steps:
- emerge -b =sys-power-5.4/acpi_call-3.17
requires:
- category: "sys-kernel"
  version:  "5.4.1"
  name:     "linux-sabayon"
- category: "sys-kernel"
  version:  "5.4.1"
  name:     "sabayon-sources"

includes:
- /usr/portage/packages/.*

