steps:
- emerge -b =net-wireless-4.20/broadcom-sta-6.30.223.271-r6
requires:
- category: "sys-kernel"
  version:  "4.20.17"
  name:     "linux-sabayon"
- category: "sys-kernel"
  version:  "4.20.17"
  name:     "sabayon-sources"

includes:
- /usr/portage/packages/.*

