steps:
- emerge -b =net-firewall-3.16/rtsp-conntrack-4.18
requires:
- category: "sys-kernel"
  version:  "3.16.57"
  name:     "linux-sabayon"
- category: "sys-kernel"
  version:  "3.16.57"
  name:     "sabayon-sources"

includes:
- /usr/portage/packages/.*

