steps:
- emerge -b =sys-power-4.14/acpi_call-3.17
requires:
- category: "sys-kernel"
  version:  "4.14.132"
  name:     "linux-sabayon"
- category: "sys-kernel"
  version:  "4.14.132"
  name:     "sabayon-sources"

includes:
- /usr/portage/packages/.*

