steps:
- emerge -b =net-firewall-4.9/rtsp-conntrack-4.18
requires:
- category: "sys-kernel"
  version:  "4.9.133"
  name:     "linux-sabayon"
- category: "sys-kernel"
  version:  "4.9.133"
  name:     "sabayon-sources"

includes:
- /usr/portage/packages/.*

