steps:
- emerge -b =sys-fs-4.19/zfs-kmod-0.8.2
requires:
- category: "sys-kernel"
  version:  "4.19.59"
  name:     "linux-sabayon"
- category: "sys-kernel"
  version:  "4.19.59"
  name:     "sabayon-sources"

includes:
- /usr/portage/packages/.*

