steps:
- emerge -b =sys-power-5.4/bbswitch-0.8-r2
requires:
- category: "sys-kernel"
  version:  "5.4.2"
  name:     "linux-sabayon"
- category: "sys-kernel"
  version:  "5.4.2"
  name:     "sabayon-sources"

includes:
- /usr/portage/packages/.*

