steps:
- emerge -b =x11-drivers-4.9/nvidia-drivers-390.87-r2
requires:
- category: "sys-kernel"
  version:  "4.9.109"
  name:     "linux-sabayon"
- category: "sys-kernel"
  version:  "4.9.109"
  name:     "sabayon-sources"

includes:
- /usr/portage/packages/.*

