steps:
- emerge -b =app-emulation-4.4/virtualbox-guest-additions-6.0.14
requires:
- category: "sys-kernel"
  version:  "4.4.166"
  name:     "linux-sabayon"
- category: "sys-kernel"
  version:  "4.4.166"
  name:     "sabayon-sources"

includes:
- /usr/portage/packages/.*

