steps:
- emerge -b =app-laptop-4.19/tp_smapi-0.43
requires:
- category: "sys-kernel"
  version:  "4.19.81"
  name:     "linux-sabayon"
- category: "sys-kernel"
  version:  "4.19.81"
  name:     "sabayon-sources"

includes:
- /usr/portage/packages/.*

