steps:
- emerge -b =sys-power-4.4/bbswitch-0.8-r2
requires:
- category: "sys-kernel"
  version:  "4.4.162"
  name:     "linux-sabayon"
- category: "sys-kernel"
  version:  "4.4.162"
  name:     "sabayon-sources"

includes:
- /usr/portage/packages/.*

