steps:
- emerge -b =net-firewall-5.3/rtsp-conntrack-4.18
requires:
- category: "sys-kernel"
  version:  "5.3.1"
  name:     "linux-sabayon"
- category: "sys-kernel"
  version:  "5.3.1"
  name:     "sabayon-sources"

includes:
- /usr/portage/packages/.*

