steps:
- emerge -b =net-vpn-3.16/wireguard-0.0.20190406-r1
requires:
- category: "sys-kernel"
  version:  "3.16.57"
  name:     "linux-sabayon"
- category: "sys-kernel"
  version:  "3.16.57"
  name:     "sabayon-sources"

includes:
- /usr/portage/packages/.*

