steps:
- emerge -b =app-laptop-5.3/tp_smapi-0.43
requires:
- category: "sys-kernel"
  version:  "5.3.7"
  name:     "linux-sabayon"
- category: "sys-kernel"
  version:  "5.3.7"
  name:     "sabayon-sources"

includes:
- /usr/portage/packages/.*

