steps:
- emerge -b =x11-drivers-4.19/nvidia-drivers-430.26
requires:
- category: "sys-kernel"
  version:  "4.19.59"
  name:     "linux-sabayon"
- category: "sys-kernel"
  version:  "4.19.59"
  name:     "sabayon-sources"

includes:
- /usr/portage/packages/.*

