steps:
- emerge -b =sys-power-4.9/bbswitch-0.8-r2
requires:
- category: "sys-kernel"
  version:  "4.9.151"
  name:     "linux-sabayon"
- category: "sys-kernel"
  version:  "4.9.151"
  name:     "sabayon-sources"

includes:
- /usr/portage/packages/.*

