steps:
- emerge -b =media-video-5.3/v4l2loopback-0.12.1
requires:
- category: "sys-kernel"
  version:  "5.3.16"
  name:     "linux-sabayon"
- category: "sys-kernel"
  version:  "5.3.16"
  name:     "sabayon-sources"

includes:
- /usr/portage/packages/.*

