steps:
- emerge -b =sys-power-4.9/acpi_call-3.17
requires:
- category: "sys-kernel"
  version:  "4.9.183"
  name:     "linux-sabayon"
- category: "sys-kernel"
  version:  "4.9.183"
  name:     "sabayon-sources"

includes:
- /usr/portage/packages/.*

