steps:
- emerge -b =media-video-4.9/v4l2loopback-0.12.1
requires:
- category: "sys-kernel"
  version:  "4.9.148"
  name:     "linux-sabayon"
- category: "sys-kernel"
  version:  "4.9.148"
  name:     "sabayon-sources"

includes:
- /usr/portage/packages/.*

