steps:
- emerge -b =app-emulation-5.4/virtualbox-modules-6.0.14
requires:
- category: "sys-kernel"
  version:  "5.4.1"
  name:     "linux-sabayon"
- category: "sys-kernel"
  version:  "5.4.1"
  name:     "sabayon-sources"

includes:
- /usr/portage/packages/.*

