steps:
- emerge -b =app-laptop-4.20/tp_smapi-0.43
requires:
- category: "sys-kernel"
  version:  "4.20.16"
  name:     "linux-sabayon"
- category: "sys-kernel"
  version:  "4.20.16"
  name:     "sabayon-sources"

includes:
- /usr/portage/packages/.*

