steps:
- emerge -b =app-emulation-3.16/virtualbox-guest-additions-6.0.14
requires:
- category: "sys-kernel"
  version:  "3.16.57"
  name:     "linux-sabayon"
- category: "sys-kernel"
  version:  "3.16.57"
  name:     "sabayon-sources"

includes:
- /usr/portage/packages/.*

