steps:
- emerge -b =x11-drivers-5.3/nvidia-drivers-390.87-r2
requires:
- category: "sys-kernel"
  version:  "5.3"
  name:     "linux-sabayon"
- category: "sys-kernel"
  version:  "5.3"
  name:     "sabayon-sources"

includes:
- /usr/portage/packages/.*

