steps:
- emerge -b =x11-drivers-4.4/nvidia-drivers-340.107-r1
requires:
- category: "sys-kernel"
  version:  "4.4.175"
  name:     "linux-sabayon"
- category: "sys-kernel"
  version:  "4.4.175"
  name:     "sabayon-sources"

includes:
- /usr/portage/packages/.*

