steps:
- emerge -b =app-laptop-4.14/tp_smapi-0.43
requires:
- category: "sys-kernel"
  version:  "4.14.112"
  name:     "linux-sabayon"
- category: "sys-kernel"
  version:  "4.14.112"
  name:     "sabayon-sources"

includes:
- /usr/portage/packages/.*

