steps:
- emerge -b =net-wireless-5.4/broadcom-sta-6.30.223.271-r6
requires:
- category: "sys-kernel"
  version:  "5.4.1"
  name:     "linux-sabayon"
- category: "sys-kernel"
  version:  "5.4.1"
  name:     "sabayon-sources"

includes:
- /usr/portage/packages/.*

