steps:
- emerge -b =x11-drivers-5.3/nvidia-drivers-430.26
requires:
- category: "sys-kernel"
  version:  "5.3.11"
  name:     "linux-sabayon"
- category: "sys-kernel"
  version:  "5.3.11"
  name:     "sabayon-sources"

includes:
- /usr/portage/packages/.*

