steps:
- emerge -b =app-laptop-3.16/tp_smapi-0.43
requires:
- category: "sys-kernel"
  version:  "3.16.56"
  name:     "linux-sabayon"
- category: "sys-kernel"
  version:  "3.16.56"
  name:     "sabayon-sources"

includes:
- /usr/portage/packages/.*

