steps:
- emerge -b =sys-fs-4.14/vhba-20190410
requires:
- category: "sys-kernel"
  version:  "4.14.129"
  name:     "linux-sabayon"
- category: "sys-kernel"
  version:  "4.14.129"
  name:     "sabayon-sources"

includes:
- /usr/portage/packages/.*

