steps:
- emerge -b =media-video-3.16/v4l2loopback-0.12.1
requires:
- category: "sys-kernel"
  version:  "3.16.57"
  name:     "linux-sabayon"
- category: "sys-kernel"
  version:  "3.16.57"
  name:     "sabayon-sources"

includes:
- /usr/portage/packages/.*

