steps:
- emerge -b =x11-drivers-3.16/nvidia-drivers-430.26
requires:
- category: "sys-kernel"
  version:  "3.16.56"
  name:     "linux-sabayon"
- category: "sys-kernel"
  version:  "3.16.56"
  name:     "sabayon-sources"

includes:
- /usr/portage/packages/.*

