steps:
- emerge -b =net-firewall-5.4/rtsp-conntrack-4.18
requires:
- category: "sys-kernel"
  version:  "5.4"
  name:     "linux-sabayon"
- category: "sys-kernel"
  version:  "5.4"
  name:     "sabayon-sources"

includes:
- /usr/portage/packages/.*

