steps:
- emerge -b =x11-drivers-5.3/nvidia-drivers-340.107-r1
requires:
- category: "sys-kernel"
  version:  "5.3.1"
  name:     "linux-sabayon"
- category: "sys-kernel"
  version:  "5.3.1"
  name:     "sabayon-sources"

includes:
- /usr/portage/packages/.*

