steps:
- emerge -b =net-vpn-4.19/wireguard-0.0.20190406-r1
requires:
- category: "sys-kernel"
  version:  "4.19.55"
  name:     "linux-sabayon"
- category: "sys-kernel"
  version:  "4.19.55"
  name:     "sabayon-sources"

includes:
- /usr/portage/packages/.*

