steps:
- emerge -b =app-emulation-4.14/virtualbox-modules-6.0.14
requires:
- category: "sys-kernel"
  version:  "4.14.144"
  name:     "linux-sabayon"
- category: "sys-kernel"
  version:  "4.14.144"
  name:     "sabayon-sources"

includes:
- /usr/portage/packages/.*

