steps:
- emerge -b =sys-fs-5.4/zfs-kmod-0.8.2
requires:
- category: "sys-kernel"
  version:  "5.4.2"
  name:     "linux-sabayon"
- category: "sys-kernel"
  version:  "5.4.2"
  name:     "sabayon-sources"

includes:
- /usr/portage/packages/.*

