steps:
- emerge -b =net-vpn-5.3/wireguard-0.0.20190406-r1
requires:
- category: "sys-kernel"
  version:  "5.3.7"
  name:     "linux-sabayon"
- category: "sys-kernel"
  version:  "5.3.7"
  name:     "sabayon-sources"

includes:
- /usr/portage/packages/.*

